# Generated by Django 3.0.6 on 2020-12-27 03:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land1029',
            fields=[
                ('gid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('objectid_1', models.BigIntegerField(blank=True, null=True)),
                ('objectid_2', models.BigIntegerField(blank=True, null=True)),
                ('objectid', models.BigIntegerField(blank=True, null=True)),
                ('block_name', models.CharField(blank=True, max_length=100, null=True)),
                ('block_use', models.CharField(blank=True, max_length=50, null=True)),
                ('block_area', models.DecimalField(decimal_places=6, max_digits=15)),
                ('block_leng', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('floor_area', models.DecimalField(decimal_places=6, max_digits=15)),
                ('arc_area', models.FloatField()),
                ('density', models.FloatField()),
                ('far', models.DecimalField(decimal_places=6, max_digits=15)),
                ('shape_idx', models.FloatField()),
                ('shape_leng', models.DecimalField(decimal_places=6, max_digits=15)),
                ('shape_le_1', models.DecimalField(decimal_places=6, max_digits=15)),
                ('shape_area', models.DecimalField(decimal_places=6, max_digits=15)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
