# Generated by Django 3.0.6 on 2020-12-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land1029',
            options={'managed': False},
        ),
    ]
